"use client";

import { useState, type FormEvent } from "react";

import type { AdminLocale } from "./admin-locale";

type Rate = { productCode:string; productName:string; amount:number; currency:string; origin:string };
type Row = { quantity:number; weightGrams:number; lengthMm:number; widthMm:number; heightMm:number; referenceVolumetricKg:Record<"5000"|"6000"|"8000"|"12000",number>; status:string; rates:Rate[] };
type Spot = { serviceKey:string; productCode:string; productName:string; currency:string; origin:string; recommendedQuantity:number; totalAmount:number; amountPerItem:number; savingsVersusSeparate:number };

const copy = {
  en: { title:"Weight, volume & bundle optimizer", intro:"Identical-SKU simulation only. Runs one read-only YunExpress price trial for each quantity and compares the same service, currency and origin.", country:"Country", postal:"Postal code", weight:"Unit weight incl. gift box (g)", length:"Unit length (mm)", width:"Unit width (mm)", height:"Unit height (mm)", carton:"Outer carton weight (g)", padding:"Outer padding (mm/side)", quantity:"Test up to", run:"Analyze 1–6 items", qty:"Items", packed:"Estimated packed parcel", actual:"Actual weight", volume:"Reference volumetric range", cheapest:"Lowest rate in each currency", perItem:"Per item", sweet:"Same-service sweet spots", service:"Service", saving:"Saving vs separate parcels", note:"Reference only: the 5000–12000 range is mathematical, not the selected service's billing formula. The tool sends one consolidated parcel (pieces=1); warehouse packing must confirm the final carton before charging a customer.", failed:"Optimization failed. Check provider connection and parcel inputs." },
  zh: { title:"重量、体积与合箱甜蜜点", intro:"仅模拟同一 SKU。每个数量调用一次云途只读试算，并按同一线路、币种和发货仓比较。", country:"国家", postal:"邮编", weight:"单件含礼盒重量（克）", length:"单件长度（毫米）", width:"单件宽度（毫米）", height:"单件高度（毫米）", carton:"合箱外箱重量（克）", padding:"外箱每边余量（毫米）", quantity:"最多测试件数", run:"分析 1–6 件", qty:"件数", packed:"估算合箱包裹", actual:"实重", volume:"参考体积重范围", cheapest:"各币种最低报价", perItem:"每件均摊", sweet:"同线路甜蜜点", service:"物流服务", saving:"较分开发货节省", note:"仅供参考：5000–12000 是数学范围，不代表所选线路的实际计费公式。本工具按一个合箱包裹（pieces=1）试算；向顾客收费前仍需仓库确认最终外箱。", failed:"分析失败，请检查云途连接和包裹参数。" },
} as const;

export function YunExpressShippingOptimizer({ locale }: { locale: AdminLocale }) {
  const t=copy[locale], [rows,setRows]=useState<Row[]>([]), [spots,setSpots]=useState<Spot[]>([]), [busy,setBusy]=useState(false), [message,setMessage]=useState("");
  const run=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setRows([]);setSpots([]);setMessage("");const data=new FormData(event.currentTarget);try{const response=await fetch("/api/admin/retail/shipping/provider/optimize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({countryCode:String(data.get("countryCode")).toUpperCase(),postalCode:String(data.get("postalCode")),unitWeightGrams:Number(data.get("unitWeightGrams")),unitLengthMm:Number(data.get("unitLengthMm")),unitWidthMm:Number(data.get("unitWidthMm")),unitHeightMm:Number(data.get("unitHeightMm")),outerPackagingWeightGrams:Number(data.get("outerPackagingWeightGrams")),outerPaddingMm:Number(data.get("outerPaddingMm")),maxQuantity:Number(data.get("maxQuantity")),packageType:"C"})});const body=await response.json().catch(()=>({}));if(!response.ok||!body.ok){setMessage(body.providerStatus?`${t.failed} (${body.providerStatus})`:t.failed);return;}setRows(body.rows??[]);setSpots(body.sweetSpots??[]);}catch{setMessage(t.failed);}finally{setBusy(false);}};
  const input="mt-1 w-full rounded-lg border border-[#cdbda9] bg-white p-2.5";
  const lowestByCurrency=(rates:Rate[])=>[...rates.reduce((map,rate)=>{const current=map.get(rate.currency);if(!current||rate.amount<current.amount)map.set(rate.currency,rate);return map;},new Map<string,Rate>()).values()].sort((a,b)=>a.currency.localeCompare(b.currency));
  const visibleSpots=[...spots.reduce((map,spot)=>{const group=map.get(spot.currency)??[];if(group.length<5)group.push(spot);map.set(spot.currency,group);return map;},new Map<string,Spot[]>()).values()].flat();
  return <div className="mt-7 border-t border-[#dfd2c0] pt-5"><h3 className="font-semibold">{t.title}</h3><p className="mt-1 max-w-4xl text-sm text-muted">{t.intro}</p>
    <form className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-5" onSubmit={run}>
      {[["countryCode",t.country,"US","text",undefined],["postalCode",t.postal,"10001","text",undefined],["unitWeightGrams",t.weight,"250","number",1],["unitLengthMm",t.length,"160","number",1],["unitWidthMm",t.width,"110","number",1],["unitHeightMm",t.height,"55","number",1],["outerPackagingWeightGrams",t.carton,"80","number",0],["outerPaddingMm",t.padding,"10","number",0],["maxQuantity",t.quantity,"6","number",2]].map(([name,label,value,type,min])=><label className="text-sm" key={String(name)}>{label}<input className={input} defaultValue={String(value)} name={String(name)} type={String(type)} min={min as number|undefined} max={name==="maxQuantity"?6:undefined} required={name!=="postalCode"}/></label>)}
      <div className="flex items-end"><button className="rounded-lg bg-accent px-4 py-2.5 text-sm text-white disabled:opacity-60" disabled={busy}>{busy?"…":t.run}</button></div>
    </form><p className="mt-3 text-xs text-muted">{t.note}</p>{message&&<p className="mt-3 text-sm text-red-700" role="alert">{message}</p>}
    {rows.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">{t.qty}</th><th className="p-2">{t.packed}</th><th className="p-2">{t.actual}</th><th className="p-2">{t.volume}</th><th className="p-2">{t.cheapest}</th><th className="p-2">{t.perItem}</th></tr></thead><tbody>{rows.map((row)=>{const cheapest=lowestByCurrency(row.rates);return <tr className="border-t" key={row.quantity}><td className="p-2">{row.quantity}</td><td className="p-2">{row.lengthMm}×{row.widthMm}×{row.heightMm} mm</td><td className="p-2">{(row.weightGrams/1000).toFixed(3)} kg</td><td className="p-2">{row.referenceVolumetricKg["12000"].toFixed(3)}–{row.referenceVolumetricKg["5000"].toFixed(3)} kg</td><td className="p-2">{cheapest.length?cheapest.map((rate)=><div key={`${rate.currency}:${rate.productCode}:${rate.origin}`}>{rate.amount.toFixed(2)} {rate.currency} · {rate.productCode}</div>):row.status}</td><td className="p-2">{cheapest.map((rate)=><div key={`${rate.currency}:${rate.productCode}:${rate.origin}`}>{(rate.amount/row.quantity).toFixed(2)} {rate.currency}</div>)}</td></tr>;})}</tbody></table></div>}
    {visibleSpots.length>0&&<div className="mt-5"><h4 className="text-sm font-semibold">{t.sweet}</h4><div className="mt-2 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">{t.service}</th><th className="p-2">{t.qty}</th><th className="p-2">{t.perItem}</th><th className="p-2">{t.saving}</th></tr></thead><tbody>{visibleSpots.map((spot)=><tr className="border-t" key={spot.serviceKey}><td className="p-2">{spot.productName||spot.productCode} ({spot.productCode}) · {spot.origin||"—"}</td><td className="p-2">{spot.recommendedQuantity}</td><td className="p-2">{spot.amountPerItem.toFixed(2)} {spot.currency}</td><td className="p-2">{spot.savingsVersusSeparate.toFixed(2)} {spot.currency}</td></tr>)}</tbody></table></div></div>}
  </div>;
}
