"use client";

import { useEffect, useState, type FormEvent } from "react";

import type { AdminLocale } from "./admin-locale";
import { YunExpressShippingOptimizer } from "./yunexpress-shipping-optimizer";

type Rate = { productCode: string; productName: string; priceName: string; deliveryWindow: string; amount: number; currency: string; origin: string };
type Country = { code: string; name: string; active: boolean };
type CoverageResult = { countryCode: string; postalCode: string; status: "quote_available" | "no_eligible_service" | "provider_not_bound" | "auth_or_permission" | "provider_throttled" | "transport_timeout" | "transport_network" | "provider_unavailable" | "invalid_provider_payload" | "fixture_missing"; providerCode?: string; httpStatus?: number; rates: Rate[] };
const postalFixtures: Record<string,string> = { US:"10001",GB:"SW1A 1AA",DE:"10115",FR:"75001",IT:"00118",ES:"28001",CA:"M5V 3A8",AU:"2000",JP:"100-0001",KR:"03051",NL:"1012 JS",BE:"1000",SE:"111 20",NO:"0150",DK:"1050",FI:"00100",PL:"00-001",AT:"1010",CH:"8001",IE:"D02 X285",PT:"1000-001",CZ:"110 00",BR:"01001-000",MX:"06000",IN:"110001",SG:"018956",MY:"50000",TH:"10100",ID:"10110",PH:"1000",ZA:"8001",TR:"34000",IL:"91000",SA:"11564",KW:"13001",BH:"317",OM:"100" };
const postalOptionalCountries = new Set(["AE","HK","MO","QA"]);
const text = {
  en: { title:"YunExpress API", intro:"Verify the server-only connection and request reference rates before updating checkout zones.", connected:"Connected", unavailable:"Not connected", environment:"Environment", test:"Test connection", quote:"Get reference rates", country:"Country code", postal:"Postal code", weight:"Weight (g)", length:"Length (mm)", width:"Width (mm)", height:"Height (mm)", battery:"Contains battery", product:"Service", delivery:"Delivery", amount:"Reference total", origin:"Origin", empty:"No eligible YunExpress services were returned.", failed:"YunExpress request failed. Check credentials, permissions, or package data.", note:"Provider rates are reference-only. Review duties, currency, and contract terms before saving a customer-facing shipping zone.", coverage:"Run global read-only coverage", coverageIntro:"Tests YunExpress catalog countries that have a verified postal fixture with one standard 300 g parcel. Production mode uses read-only price trials. Missing fixtures are reported without calling YunExpress. This does not enable checkout countries or create shipments.", progress:"Tested", download:"Download JSON", available:"Quote available", unavailableCountries:"No quote / review", fixtureMissing:"Postal fixture missing", stopped:"Global test stopped at the US/DE/AE gate. Review the displayed provider status before retrying." },
  zh: { title:"云途物流 API", intro:"验证服务端连接，并在维护结账配送区域之前查询参考报价。", connected:"已连接", unavailable:"未连接", environment:"环境", test:"测试连接", quote:"查询参考报价", country:"国家二字码", postal:"邮编", weight:"重量（克）", length:"长（毫米）", width:"宽（毫米）", height:"高（毫米）", battery:"含电池", product:"物流服务", delivery:"时效", amount:"参考总价", origin:"计费地点", empty:"没有返回可用的云途物流服务。", failed:"云途请求失败，请检查凭证、权限或包裹数据。", note:"云途报价仅供参考；保存为顾客运费前，必须核对关税模式、币种和合同条款。", coverage:"运行全球只读覆盖测试", coverageIntro:"使用已核验代表邮编和统一 300 克普货包裹测试云途国家目录；生产环境仅调用只读运费试算。缺少邮编样本的国家仅标记、不调用云途。不会开放结账国家，也不会创建运单。", progress:"已测试", download:"下载 JSON", available:"可报价", unavailableCountries:"无报价 / 待核验", fixtureMissing:"缺少邮编样本", stopped:"全球测试已在 US/DE/AE 门槛停止；请根据页面显示的供应商状态处理后重试。" },
} as const;

export function YunExpressProviderPanel({ locale }: { locale: AdminLocale }) {
  const t = text[locale], [status,setStatus]=useState<{authenticated:boolean;environment:string|null}|null>(null), [rates,setRates]=useState<Rate[]>([]), [message,setMessage]=useState(""), [busy,setBusy]=useState(false), [coverageBusy,setCoverageBusy]=useState(false), [coverageTotal,setCoverageTotal]=useState(0), [coverageResults,setCoverageResults]=useState<CoverageResult[]>([]);
  const load = async () => { const response=await fetch("/api/admin/retail/shipping/provider/status",{cache:"no-store"}); const body=await response.json().catch(()=>({})); setStatus({authenticated:response.ok&&body.authenticated===true,environment:body.environment??null}); };
  useEffect(()=>{void load().catch(()=>setStatus({authenticated:false,environment:null}));},[]);
  const quote = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault();setBusy(true);setMessage("");setRates([]);const data=new FormData(event.currentTarget);try{const response=await fetch("/api/admin/retail/shipping/provider/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({countryCode:String(data.get("countryCode")).toUpperCase(),postalCode:String(data.get("postalCode")),weightGrams:Number(data.get("weightGrams")),lengthMm:Number(data.get("lengthMm")),widthMm:Number(data.get("widthMm")),heightMm:Number(data.get("heightMm")),packageType:data.get("battery")==="on"?"E":"C"})});const body=await response.json();if(!response.ok||!body.ok){setMessage(`${t.failed}${body.providerStatus?` (${body.providerStatus}${body.httpStatus?` ${body.httpStatus}`:""})`:""}`);return;}const next=(body.rates??[]) as Rate[];setRates(next);if(!next.length)setMessage(t.empty);}catch{setMessage(t.failed);}finally{setBusy(false);}};
  const runCoverage = async () => {
    setCoverageBusy(true);setCoverageResults([]);setCoverageTotal(0);setMessage("");
    try {
      const countryResponse=await fetch("/api/admin/retail/shipping/provider/countries",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});
      const countryBody=await countryResponse.json();
      if(!countryResponse.ok||!countryBody.ok)throw new Error("countries_failed");
      const active=((countryBody.countries??[]) as Country[]).filter((country)=>country.active);
      const byCode=new Map(active.map((country)=>[country.code,country]));
      const gate=["US","DE","AE"].filter((code)=>byCode.has(code));
      const remaining=active.map((country)=>country.code).filter((code)=>!gate.includes(code));
      setCoverageTotal(gate.length+remaining.length);
      const requestBatch=async(codes:string[])=>{const response=await fetch("/api/admin/retail/shipping/provider/coverage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({countries:codes.map((countryCode)=>({countryCode,postalCode:postalFixtures[countryCode]??""})),weightGrams:300,lengthMm:180,widthMm:120,heightMm:60,packageType:"C"})});const body=await response.json();if(!response.ok||!body.ok){if(body.providerStatus)return codes.map((countryCode):CoverageResult=>({countryCode,postalCode:postalFixtures[countryCode]??"",status:body.providerStatus, ...(body.httpStatus?{httpStatus:body.httpStatus}:{}),rates:[]}));throw new Error("coverage_failed");}return (body.results??[]) as CoverageResult[];};
      const gateResults=gate.length?await requestBatch(gate):[];
      setCoverageResults(gateResults);
      const hardGateFailure=gateResults.some((result)=>["auth_or_permission","provider_throttled","transport_timeout","transport_network","provider_unavailable","invalid_provider_payload"].includes(result.status));
      const unboundGate=gateResults.length===3&&gateResults.every((result)=>result.status==="provider_not_bound");
      if(gateResults.length!==3||hardGateFailure||unboundGate){setMessage(t.stopped);return;}
      const testable=remaining.filter((code)=>postalFixtures[code]!==undefined||postalOptionalCountries.has(code));
      const missing=remaining.filter((code)=>!testable.includes(code)).map((countryCode):CoverageResult=>({countryCode,postalCode:"",status:"fixture_missing",rates:[]}));
      let completed=[...gateResults,...missing];setCoverageResults(completed);
      for(let index=0;index<testable.length;index+=6){const next=await requestBatch(testable.slice(index,index+6));completed=[...completed,...next];setCoverageResults(completed);}
    } catch { setMessage(t.failed); }
    finally { setCoverageBusy(false); }
  };
  const downloadCoverage = () => { const blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),environment:status?.environment??null,package:{weightGrams:300,lengthMm:180,widthMm:120,heightMm:60,packageType:"C"},results:coverageResults},null,2)],{type:"application/json"});const href=URL.createObjectURL(blob);const link=document.createElement("a");link.href=href;link.download=`yunexpress-coverage-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(href); };
  const input="mt-1 w-full rounded-lg border border-[#cdbda9] bg-white p-2.5";
  return <section className="mb-6 rounded-xl border border-[#dfd2c0] bg-[#fbf7f1] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{t.title}</h2><p className="mt-2 max-w-3xl text-sm text-muted">{t.intro}</p></div><button className="rounded-lg border border-[#cdbda9] px-4 py-2 text-sm" onClick={()=>void load()}>{t.test}</button></div><p className="mt-3 text-sm" role="status"><span className={status?.authenticated?"text-green-700":"text-red-700"}>{status?.authenticated?t.connected:t.unavailable}</span>{status?.environment&&<> · {t.environment}: {status.environment}</>}</p>
    <form className="mt-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6" onSubmit={quote}>{[["countryCode",t.country,"US"],["postalCode",t.postal,"10001"],["weightGrams",t.weight,"300"],["lengthMm",t.length,"180"],["widthMm",t.width,"120"],["heightMm",t.height,"60"]].map(([name,label,placeholder])=><label className="text-sm" key={name}>{label}<input className={input} name={name} placeholder={placeholder} required={name!=="postalCode"} min={name.endsWith("Mm")||name==="weightGrams"?1:undefined} type={name.endsWith("Mm")||name==="weightGrams"?"number":"text"}/></label>)}<label className="flex items-center gap-2 text-sm md:col-span-2"><input name="battery" type="checkbox"/>{t.battery}</label><div className="md:col-span-2"><button className="rounded-lg bg-accent px-4 py-2.5 text-white disabled:opacity-60" disabled={busy}>{busy?"…":t.quote}</button></div></form>
    <p className="mt-3 text-xs text-muted">{t.note}</p>{message&&<p className="mt-3 text-sm" role="alert">{message}</p>}{rates.length>0&&<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">{t.product}</th><th className="p-2">{t.delivery}</th><th className="p-2">{t.amount}</th><th className="p-2">{t.origin}</th></tr></thead><tbody>{rates.map((rate)=><tr className="border-t" key={`${rate.productCode}:${rate.priceName}:${rate.currency}`}><td className="p-2">{rate.productName} ({rate.productCode})</td><td className="p-2">{rate.deliveryWindow||"—"}</td><td className="p-2">{rate.amount.toFixed(2)} {rate.currency}</td><td className="p-2">{rate.origin||"—"}</td></tr>)}</tbody></table></div>}
    <YunExpressShippingOptimizer locale={locale}/>
    <div className="mt-7 border-t border-[#dfd2c0] pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{t.coverage}</h3><p className="mt-1 max-w-3xl text-sm text-muted">{t.coverageIntro}</p></div><div className="flex gap-2"><button className="rounded-lg bg-accent px-4 py-2.5 text-sm text-white disabled:opacity-60" disabled={coverageBusy||!status?.authenticated} onClick={()=>void runCoverage()}>{coverageBusy?"…":t.coverage}</button>{coverageResults.length>0&&<button className="rounded-lg border border-[#cdbda9] px-4 py-2.5 text-sm" onClick={downloadCoverage}>{t.download}</button>}</div></div>
      {(coverageTotal>0||coverageResults.length>0)&&<p className="mt-3 text-sm" role="status">{t.progress}: {coverageResults.filter((result)=>result.status!=="fixture_missing").length}/{coverageTotal} · {t.available}: {coverageResults.filter((result)=>result.status==="quote_available").length} · {t.unavailableCountries}: {coverageResults.filter((result)=>result.status!=="quote_available"&&result.status!=="fixture_missing").length} · {t.fixtureMissing}: {coverageResults.filter((result)=>result.status==="fixture_missing").length}</p>}
      {coverageResults.length>0&&<div className="mt-4 max-h-96 overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">{t.country}</th><th className="p-2">Status</th><th className="p-2">{t.product}</th><th className="p-2">{t.amount}</th></tr></thead><tbody>{coverageResults.map((result)=><tr className="border-t" key={result.countryCode}><td className="p-2">{result.countryCode}</td><td className="p-2">{result.status}{result.providerCode?` (${result.providerCode})`:result.httpStatus?` (HTTP ${result.httpStatus})`:""}</td><td className="p-2">{result.rates[0]?.productName||"—"}</td><td className="p-2">{result.rates[0]?`${result.rates[0].amount.toFixed(2)} ${result.rates[0].currency}`:"—"}</td></tr>)}</tbody></table></div>}
    </div></section>;
}
