"use client";

import { useEffect, useState, type FormEvent } from "react";

import type { AdminLocale } from "./admin-locale";

type Rate = { productCode: string; productName: string; priceName: string; deliveryWindow: string; amount: number; currency: string; origin: string };
const text = {
  en: { title:"YunExpress API", intro:"Verify the server-only connection and request reference rates before updating checkout zones.", connected:"Connected", unavailable:"Not connected", environment:"Environment", test:"Test connection", quote:"Get reference rates", country:"Country code", postal:"Postal code", weight:"Weight (g)", length:"Length (mm)", width:"Width (mm)", height:"Height (mm)", battery:"Contains battery", product:"Service", delivery:"Delivery", amount:"Reference total", origin:"Origin", empty:"No eligible YunExpress services were returned.", failed:"YunExpress request failed. Check credentials, permissions, or package data.", note:"Provider rates are reference-only. Review duties, currency, and contract terms before saving a customer-facing shipping zone." },
  zh: { title:"云途物流 API", intro:"验证服务端连接，并在维护结账配送区域之前查询参考报价。", connected:"已连接", unavailable:"未连接", environment:"环境", test:"测试连接", quote:"查询参考报价", country:"国家二字码", postal:"邮编", weight:"重量（克）", length:"长（毫米）", width:"宽（毫米）", height:"高（毫米）", battery:"含电池", product:"物流服务", delivery:"时效", amount:"参考总价", origin:"计费地点", empty:"没有返回可用的云途物流服务。", failed:"云途请求失败，请检查凭证、权限或包裹数据。", note:"云途报价仅供参考；保存为顾客运费前，必须核对关税模式、币种和合同条款。" },
} as const;

export function YunExpressProviderPanel({ locale }: { locale: AdminLocale }) {
  const t = text[locale], [status,setStatus]=useState<{authenticated:boolean;environment:string|null}|null>(null), [rates,setRates]=useState<Rate[]>([]), [message,setMessage]=useState(""), [busy,setBusy]=useState(false);
  const load = async () => { const response=await fetch("/api/admin/retail/shipping/provider/status",{cache:"no-store"}); const body=await response.json().catch(()=>({})); setStatus({authenticated:response.ok&&body.authenticated===true,environment:body.environment??null}); };
  useEffect(()=>{void load().catch(()=>setStatus({authenticated:false,environment:null}));},[]);
  const quote = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault();setBusy(true);setMessage("");setRates([]);const data=new FormData(event.currentTarget);try{const response=await fetch("/api/admin/retail/shipping/provider/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({countryCode:String(data.get("countryCode")).toUpperCase(),postalCode:String(data.get("postalCode")),weightGrams:Number(data.get("weightGrams")),lengthMm:Number(data.get("lengthMm")),widthMm:Number(data.get("widthMm")),heightMm:Number(data.get("heightMm")),packageType:data.get("battery")==="on"?"E":"C"})});const body=await response.json();if(!response.ok||!body.ok)throw new Error("quote_failed");const next=(body.rates??[]) as Rate[];setRates(next);if(!next.length)setMessage(t.empty);}catch{setMessage(t.failed);}finally{setBusy(false);}};
  const input="mt-1 w-full rounded-lg border border-[#cdbda9] bg-white p-2.5";
  return <section className="mb-6 rounded-xl border border-[#dfd2c0] bg-[#fbf7f1] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{t.title}</h2><p className="mt-2 max-w-3xl text-sm text-muted">{t.intro}</p></div><button className="rounded-lg border border-[#cdbda9] px-4 py-2 text-sm" onClick={()=>void load()}>{t.test}</button></div><p className="mt-3 text-sm" role="status"><span className={status?.authenticated?"text-green-700":"text-red-700"}>{status?.authenticated?t.connected:t.unavailable}</span>{status?.environment&&<> · {t.environment}: {status.environment}</>}</p>
    <form className="mt-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6" onSubmit={quote}>{[["countryCode",t.country,"US"],["postalCode",t.postal,"10001"],["weightGrams",t.weight,"300"],["lengthMm",t.length,"180"],["widthMm",t.width,"120"],["heightMm",t.height,"60"]].map(([name,label,placeholder])=><label className="text-sm" key={name}>{label}<input className={input} name={name} placeholder={placeholder} required={name!=="postalCode"} min={name.endsWith("Mm")||name==="weightGrams"?1:undefined} type={name.endsWith("Mm")||name==="weightGrams"?"number":"text"}/></label>)}<label className="flex items-center gap-2 text-sm md:col-span-2"><input name="battery" type="checkbox"/>{t.battery}</label><div className="md:col-span-2"><button className="rounded-lg bg-accent px-4 py-2.5 text-white disabled:opacity-60" disabled={busy}>{busy?"…":t.quote}</button></div></form>
    <p className="mt-3 text-xs text-muted">{t.note}</p>{message&&<p className="mt-3 text-sm" role="alert">{message}</p>}{rates.length>0&&<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">{t.product}</th><th className="p-2">{t.delivery}</th><th className="p-2">{t.amount}</th><th className="p-2">{t.origin}</th></tr></thead><tbody>{rates.map((rate)=><tr className="border-t" key={`${rate.productCode}:${rate.priceName}:${rate.currency}`}><td className="p-2">{rate.productName} ({rate.productCode})</td><td className="p-2">{rate.deliveryWindow||"—"}</td><td className="p-2">{rate.amount.toFixed(2)} {rate.currency}</td><td className="p-2">{rate.origin||"—"}</td></tr>)}</tbody></table></div>}</section>;
}
