"use client";

import { useCallback, useEffect, useState } from "react";

type Locale = "en" | "zh";
type Row = { public_id: string; order_id: number; status: string; reason: string; refund_request_id: string | null; refund_status: string | null; restocked_at: string | null; requested_at: string; updated_at: string; lines: Array<{ sku: string; titleEn: string; titleAr: string; titleZh: string; quantity: number }> };
const transitions: Record<string, string[]> = { requested: ["authorized", "rejected", "cancelled"], authorized: ["in_transit", "cancelled"], in_transit: ["received", "cancelled"], received: ["inspected", "rejected"], inspected: ["approved", "rejected"], approved: ["refund_pending", "closed"], refund_pending: ["refunded"], refunded: ["closed"] };
const statusCopy: Record<string, Record<Locale, string>> = {
  requested: { en: "Requested", zh: "已申请" }, authorized: { en: "Authorized", zh: "已授权" }, in_transit: { en: "In transit", zh: "运输中" }, received: { en: "Received", zh: "已收货" }, inspected: { en: "Inspected", zh: "已检验" }, approved: { en: "Approved", zh: "已批准" }, rejected: { en: "Rejected", zh: "已拒绝" }, refund_pending: { en: "Refund pending", zh: "退款处理中" }, refunded: { en: "Refunded", zh: "已退款" }, closed: { en: "Closed", zh: "已关闭" }, cancelled: { en: "Cancelled", zh: "已取消" },
};
const copy = {
  en: { title: "Returns (RMA)", description: "Customer return requests, inspections, sellable restock, and refund linkage.", back: "Back to retail admin", language: "Language", statusFilter: "Status filter", allStatuses: "All statuses", loadFailed: "Unable to load returns.", updateFailed: "Return update failed. Refresh before retrying.", notesFailed: "Unable to load return notes.", notes: "View notes", restocked: "Sellable stock restocked", reason: "Reason", customerNote: "Customer note", adminNote: "Internal note", refundRequest: "Refund request", linked: "linked", noReturns: "No return requests.", approve: "Approve / inspect stock", mark: "Mark", restockChoice: "Restock only items verified sellable? This increases inventory once and cannot be undone.", confirmWithRestock: "Approve this return and restock the verified sellable items? This increases inventory once and cannot be undone.", confirmWithoutRestock: "Approve this return without restocking inventory?", },
  zh: { title: "退货管理（RMA）", description: "管理客户退货申请、验货、可售库存回补和退款关联。", back: "返回零售后台", language: "语言", statusFilter: "状态筛选", allStatuses: "全部状态", loadFailed: "无法加载退货记录。", updateFailed: "退货更新失败。刷新后再重试。", notesFailed: "无法加载退货备注。", notes: "查看备注", restocked: "可售库存已回补", reason: "退货原因", customerNote: "客户说明", adminNote: "内部备注", refundRequest: "退款申请", linked: "已关联", noReturns: "暂无退货申请。", approve: "批准并处理库存", mark: "标记为", restockChoice: "是否仅将已确认可销售的商品回补库存？该操作只会执行一次，且不可撤销。", confirmWithRestock: "确认批准该退货并回补已确认可销售的商品库存？该操作只会执行一次，且不可撤销。", confirmWithoutRestock: "确认批准该退货，但不回补库存？", },
} as const;

function initialLocale(): Locale { if (typeof window === "undefined") return "en"; return window.localStorage.getItem("retail_admin_locale") === "zh" ? "zh" : "en"; }
function label(status: string, locale: Locale) { return statusCopy[status]?.[locale] ?? status; }

export function RetailReturns() {
  const [locale, setLocale] = useState<Locale>(initialLocale); const t = copy[locale];
  const [returns, setReturns] = useState<Row[]>([]); const [status, setStatus] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [canViewNotes, setCanViewNotes] = useState(false); const [notes, setNotes] = useState<Record<string, { customerNote: string; adminNote: string }>>({});
  const chooseLocale = (next: Locale) => { setLocale(next); window.localStorage.setItem("retail_admin_locale", next); };
  const load = useCallback(async () => { try { const response = await fetch(`/api/admin/retail/returns${status ? `?status=${encodeURIComponent(status)}` : ""}`, { cache: "no-store" }); if (!response.ok) throw new Error(); const body = await response.json(); setReturns(body.returns ?? []); setCanViewNotes(body.canViewNotes === true); setNotes({}); setMessage(""); } catch { setMessage(copy[locale].loadFailed); } }, [locale, status]);
  useEffect(() => { void load(); }, [load]);
  const move = async (row: Row, next: string) => {
    let sellableRestock = false;
    if (row.status === "inspected" && next === "approved") {
      sellableRestock = window.confirm(t.restockChoice);
      if (!window.confirm(sellableRestock ? t.confirmWithRestock : t.confirmWithoutRestock)) return;
    }
    setBusy(row.public_id);
    try { const response = await fetch(`/api/admin/retail/returns/${row.public_id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: next, adminNote: "", sellableRestock, idempotencyKey: crypto.randomUUID() }) }); if (!response.ok) throw new Error(); await load(); } catch { setMessage(t.updateFailed); } finally { setBusy(null); }
  };
  const loadNotes = async (row: Row) => { setBusy(row.public_id); try { const response = await fetch(`/api/admin/retail/returns/${row.public_id}/notes`, { cache: "no-store" }); if (!response.ok) throw new Error(); const body = await response.json(); setNotes((previous) => ({ ...previous, [row.public_id]: body.notes })); } catch { setMessage(t.notesFailed); } finally { setBusy(null); } };
  const finalStatuses = Object.keys(transitions).concat(["rejected", "closed", "cancelled"]).filter((item, index, all) => all.indexOf(item) === index);
  return <main className="mx-auto max-w-7xl px-5 py-7 sm:px-8">
    <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><a className="text-sm text-[#6b7a51] hover:underline" href="/admin/retail/overview">← {t.back}</a><h1 className="noor-title mt-3 text-3xl">{t.title}</h1><p className="mt-2 text-sm text-muted">{t.description}</p></div><label className="text-sm">{t.language}<select aria-label={t.language} className="ml-2 rounded border p-2" value={locale} onChange={(event) => chooseLocale(event.target.value as Locale)}><option value="en">English</option><option value="zh">中文</option></select></label></div>
    <label className="block max-w-xs text-sm">{t.statusFilter}<select className="mt-1 w-full rounded border p-2" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{t.allStatuses}</option>{finalStatuses.map((item) => <option value={item} key={item}>{label(item, locale)}</option>)}</select></label>
    {message && <p className="mt-4 text-sm" role="status">{message}</p>}<div className="mt-6 space-y-4">{returns.map((row) => <article className="rounded-xl border border-[#dfd2c0] bg-[#fbf7f1] p-5" key={row.public_id}><header className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">RMA {row.public_id.slice(0, 8)} · Order #{row.order_id}</h2><p className="mt-1 text-sm text-muted">{label(row.status, locale)} · {new Date(row.requested_at).toLocaleString(locale)}</p></div>{row.restocked_at && <span className="rounded bg-[#e5eed6] px-2 py-1 text-xs">{t.restocked}</span>}</header><p className="mt-3 text-sm"><strong>{t.reason}:</strong> {row.reason}</p>{canViewNotes && <div className="mt-3 text-sm">{notes[row.public_id] ? <><p><strong>{t.customerNote}:</strong> {notes[row.public_id].customerNote}</p><p className="mt-1"><strong>{t.adminNote}:</strong> {notes[row.public_id].adminNote}</p></> : <button className="rounded border border-[#cdbda9] px-3 py-1.5 disabled:opacity-50" disabled={busy === row.public_id} onClick={() => void loadNotes(row)}>{t.notes}</button>}</div>}<ul className="mt-3 list-disc pl-5 text-sm">{row.lines.map((line) => <li key={`${row.public_id}-${line.sku}`}>{locale === "zh" ? line.titleZh || line.titleEn : line.titleEn || line.titleZh} ({line.sku}) ×{line.quantity}</li>)}</ul>{row.refund_request_id && <p className="mt-3 text-sm">{t.refundRequest}: {row.refund_status ? label(row.refund_status, locale) : t.linked}</p>}<div className="mt-4 flex flex-wrap gap-2">{(transitions[row.status] ?? []).map((next) => <button className="rounded border border-[#cdbda9] px-3 py-1.5 text-sm disabled:opacity-50" key={next} disabled={busy === row.public_id} onClick={() => void move(row, next)}>{next === "approved" && row.status === "inspected" ? t.approve : `${t.mark} ${label(next, locale)}`}</button>)}</div></article>)}{!returns.length && <p className="text-sm text-muted">{t.noReturns}</p>}</div>
  </main>;
}
