"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type ChangeEvent, type ReactNode } from "react";

import { AdminShell } from "../ui";

type Locale = "en" | "zh";
export type SettlementView = "imports" | "transactions" | "payouts" | "exceptions";
type Row = Record<string, unknown>;
type SettlementResponse = { ok: boolean; error?: string; import?: Row; imports?: Row[]; exceptions?: Row[]; transactions?: Row[]; matches?: Row[]; payouts?: Row[]; payoutItems?: Row[] };

const copy = {
  en: {
    title:"PayPal settlement reconciliation", description:"Import PayPal CSV or JSON reports, review ledger matches, and resolve exceptions. Imported reports never change the order payment truth.",
    back:"Back to finance", language:"Language", refresh:"Refresh", imports:"Import runs", transactions:"Transactions & matches", payouts:"Payouts", exceptions:"Exception review",
    loading:"Loading…", loadFailed:"Could not load settlement data.", noRecords:"No records.", sourceFile:"PayPal report file", choose:"Choose CSV or JSON", review:"Review import", confirmImport:"Confirm import", cancel:"Cancel", importTitle:"Manual report import (backup)", importHelp:"Use this only for historical files or when PayPal API access is unavailable. Maximum 1 MiB and 10,000 records; raw content and customer data are not stored.", autoSync:"Sync from PayPal", syncHelp:"Read transaction and fee records directly from PayPal Reporting. This is read-only at PayPal and never changes an order or payment.", syncDays:"Date range", syncNow:"Sync now", syncing:"Syncing…", syncComplete:"PayPal sync completed and readback confirmed.", syncEmpty:"Sync completed; no new USD transactions were returned.", permissionRequired:"PayPal Reporting permission is not enabled for this app. Keep using manual reports until PayPal enables it.",
    selected:"Selected", format:"Format", size:"Size", confirmImportPrompt:"Import this report for reconciliation? This records normalized accounting evidence and may mark exact ledger matches as reconciled.", importing:"Importing…", imported:"Import completed and readback confirmed.", importFailed:"Import failed. No success is assumed.", readbackFailed:"The write may have succeeded, but readback failed. Refresh before retrying.",
    file:"File", rows:"Rows", importedBy:"Imported by", importedAt:"Imported at", openExceptions:"Open exceptions", hash:"File hash", transactionId:"Transaction ID", type:"Type", status:"Status", occurred:"Occurred", gross:"Gross", fee:"Fee", net:"Net", captureId:"Capture ID", matchCount:"Matches", matchKind:"Match kind", ledgerPosting:"Ledger posting", reference:"Reference",
    payoutId:"Payout ID", payoutItemId:"Payout item ID", amount:"Amount", items:"Payout items", code:"Reason", state:"State", created:"Created", closeNote:"Review note", close:"Close exception", closing:"Closing…", closed:"Exception closed and readback confirmed.", closeFailed:"Exception close failed.", closePrompt:"Close this exception after completing the manual review? This does not alter any order or payment posting.", showOpen:"Open", showClosed:"Closed", normalizedOnly:"Only normalized, non-customer accounting fields are shown. Raw report payloads and PII are never rendered.",
  },
  zh: {
    title:"PayPal 结算对账", description:"导入 PayPal CSV 或 JSON 报表，检查账本匹配并处理异常。导入报表不会改变订单的支付事实。",
    back:"返回财务", language:"语言", refresh:"刷新", imports:"导入记录", transactions:"交易与匹配", payouts:"Payout 结算", exceptions:"异常审核",
    loading:"加载中…", loadFailed:"无法加载结算数据。", noRecords:"暂无记录。", sourceFile:"PayPal 报表文件", choose:"选择 CSV 或 JSON", review:"检查导入", confirmImport:"确认导入", cancel:"取消", importTitle:"手工报表导入（备用）", importHelp:"仅用于历史文件或 PayPal API 暂不可用时。最大 1 MiB、10,000 条记录；系统不保存原始内容或客户资料。", autoSync:"从 PayPal 自动同步", syncHelp:"通过 PayPal Reporting API 只读获取交易和手续费记录；不会在 PayPal 创建操作，也不会改变订单或付款。", syncDays:"同步范围", syncNow:"立即同步", syncing:"正在同步…", syncComplete:"PayPal 同步完成，并已通过重新读取确认。", syncEmpty:"同步完成；此范围内没有新的美元交易。", permissionRequired:"当前 PayPal 应用尚未开通 Reporting 权限。开通前仍可使用手工报表。",
    selected:"已选择", format:"格式", size:"大小", confirmImportPrompt:"确认导入这份报表用于对账吗？系统会记录规范化会计凭据，并可能把完全匹配的账本分录标记为已对账。", importing:"正在导入…", imported:"导入完成，并已通过重新读取确认。", importFailed:"导入失败，系统不会假定写入成功。", readbackFailed:"写入可能已成功，但重新读取失败。请刷新确认后再重试。",
    file:"文件", rows:"行数", importedBy:"导入人", importedAt:"导入时间", openExceptions:"未处理异常", hash:"文件哈希", transactionId:"交易 ID", type:"类型", status:"状态", occurred:"发生时间", gross:"总额", fee:"手续费", net:"净额", captureId:"Capture ID", matchCount:"匹配数", matchKind:"匹配类型", ledgerPosting:"账本分录", reference:"关联号",
    payoutId:"Payout ID", payoutItemId:"Payout Item ID", amount:"金额", items:"Payout 明细", code:"异常原因", state:"状态", created:"创建时间", closeNote:"审核备注", close:"关闭异常", closing:"正在关闭…", closed:"异常已关闭，并已通过重新读取确认。", closeFailed:"关闭异常失败。", closePrompt:"确认人工审核完成并关闭此异常吗？此操作不会修改订单或支付分录。", showOpen:"待处理", showClosed:"已关闭", normalizedOnly:"页面只显示规范化后的非客户会计字段，绝不呈现原始报表载荷或个人信息。",
  },
} as const;

async function requestJson(path:string,init?:RequestInit):Promise<SettlementResponse>{const response=await fetch(path,{...init,cache:"no-store",headers:{"content-type":"application/json",...(init?.headers??{})}});const body=await response.json().catch(()=>({ok:false}));if(!response.ok||!body.ok)throw new Error(String(body.error??"request_failed"));return body;}
const value=(row:Row,key:string)=>row[key]===null||row[key]===undefined?"—":String(row[key]);
const date=(input:unknown,locale:Locale)=>input?new Intl.DateTimeFormat(locale==="zh"?"zh-CN":"en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(input))):"—";
const money=(input:unknown,currency:unknown,locale:Locale)=>input===null||input===undefined?"—":new Intl.NumberFormat(locale==="zh"?"zh-CN":"en",{style:"currency",currency:String(currency||"USD")}).format(Number(input)/100);
const sectionClass="rounded-2xl border border-[#ded2c4] bg-white p-5 shadow-sm";
const tableClass="min-w-full divide-y divide-[#e5dbcf] text-left text-sm";

function Table({headers,rows,render}:{headers:string[];rows:Row[];render:(row:Row)=>ReactNode}){return <div className="overflow-x-auto"><table className={tableClass}><thead><tr>{headers.map((header)=><th key={header} className="whitespace-nowrap px-3 py-3 font-medium text-[#6f6255]">{header}</th>)}</tr></thead><tbody className="divide-y divide-[#eee6dc]">{rows.map((row,index)=><tr key={String(row.id??row.paypal_transaction_id??row.paypal_payout_id??index)}>{render(row)}</tr>)}</tbody></table></div>}
const Cell=({children,mono=false}:{children:ReactNode;mono?:boolean})=><td className={`whitespace-nowrap px-3 py-3 align-top ${mono?"font-mono text-xs":""}`}>{children}</td>;

export function SettlementConsole({view}:{view:SettlementView}){
  const [locale,setLocale]=useState<Locale>("en"),[data,setData]=useState<SettlementResponse>({ok:true}),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[stateFilter,setStateFilter]=useState<"open"|"closed">("open"),[syncDays,setSyncDays]=useState(7);
  const [file,setFile]=useState<File|null>(null),[reviewing,setReviewing]=useState(false),[busy,setBusy]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
  const importKey=useRef(crypto.randomUUID()),closeKeys=useRef(new Map<string,string>()),writing=useRef(false); const text=copy[locale];
  useEffect(()=>{const saved=localStorage.getItem("retail_admin_locale");if(saved==="zh"||saved==="en")setLocale(saved)},[]);
  const changeLocale=(next:Locale)=>{setLocale(next);localStorage.setItem("retail_admin_locale",next)};
  const load=useCallback(async(filter: "open"|"closed"=stateFilter)=>{setLoading(true);try{const next=await requestJson(`/api/admin/retail/settlements?state=${filter}&limit=100&offset=0`);setData(next);setMessage("");return next}catch{setMessage(copy[locale].loadFailed);return null}finally{setLoading(false)}},[locale,stateFilter]);
  useEffect(()=>{void load(stateFilter)},[load,stateFilter]);
  const chooseFile=(event:ChangeEvent<HTMLInputElement>)=>{const next=event.target.files?.[0]??null;setFile(next);setReviewing(false);setMessage("");importKey.current=crypto.randomUUID()};
  const importReport=async()=>{if(!file||writing.current||!window.confirm(text.confirmImportPrompt))return;writing.current=true;setBusy(true);setMessage("");try{const format=file.name.toLowerCase().endsWith(".json")?"json":"csv";const content=await file.text();const written=await requestJson("/api/admin/retail/settlements",{method:"POST",body:JSON.stringify({filename:file.name,format,content,idempotencyKey:importKey.current})});const id=String(written.import?.import_id??written.import?.id??"");const readback=await load(stateFilter);if(!readback||!id||!(readback.imports??[]).some((row)=>String(row.id)===id)){setMessage(text.readbackFailed)}else{setMessage(text.imported);setFile(null);setReviewing(false);importKey.current=crypto.randomUUID()}}catch{setMessage(text.importFailed)}finally{writing.current=false;setBusy(false)}};
  const syncReport=async()=>{if(writing.current)return;writing.current=true;setBusy(true);setMessage("");const idempotencyKey=crypto.randomUUID();try{const response=await fetch("/api/admin/retail/settlements/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({days:syncDays,idempotencyKey})});const body=await response.json().catch(()=>({}));if(!response.ok||!body.ok){if(body.error==="paypal_reporting_permission_required")setMessage(text.permissionRequired);else setMessage(text.importFailed);return}const readback=await load(stateFilter);if(!readback){setMessage(text.readbackFailed);return}const importedId=String(body.imported?.import_id??body.imported?.id??"");if(Number(body.rowCount)>0&&(!importedId||!(readback.imports??[]).some((row)=>String(row.id)===importedId))){setMessage(text.readbackFailed);return}setMessage(Number(body.rowCount)>0?text.syncComplete:text.syncEmpty)}catch{setMessage(text.importFailed)}finally{writing.current=false;setBusy(false)}};
  const closeException=async(id:string)=>{const note=(notes[id]??"").trim();if(!note||writing.current||!window.confirm(text.closePrompt))return;writing.current=true;setBusy(true);setMessage("");let key=closeKeys.current.get(id);if(!key){key=crypto.randomUUID();closeKeys.current.set(id,key)}try{await requestJson(`/api/admin/retail/settlements/exceptions/${id}/close`,{method:"POST",body:JSON.stringify({note,idempotencyKey:key})});const readback=await load(stateFilter);const confirmed=Boolean(readback)&&(stateFilter==="open"?!(readback!.exceptions??[]).some((row)=>String(row.id)===id):(readback!.exceptions??[]).some((row)=>String(row.id)===id&&row.state==="closed"));if(!confirmed)setMessage(text.readbackFailed);else{closeKeys.current.delete(id);setNotes((current)=>({...current,[id]:""}));setMessage(text.closed)}}catch{setMessage(text.closeFailed)}finally{writing.current=false;setBusy(false)}};
  const nav:[SettlementView,string][]=[["imports",text.imports],["transactions",text.transactions],["payouts",text.payouts],["exceptions",text.exceptions]];
  return <AdminShell section="settlements" locale={locale} onLocale={changeLocale} refresh={()=>void load(stateFilter)}><div className="min-h-screen bg-[#f7f2eb] text-[#2f2923]"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
    <header className="mb-5 rounded-2xl bg-[#2f2923] p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/admin/retail/finance" className="text-sm text-[#e9dccd] hover:text-white">← {text.back}</Link><h1 className="mt-2 font-serif text-3xl">{text.title}</h1><p className="mt-2 max-w-3xl text-sm text-[#e9dccd]">{text.description}</p></div><button className="rounded-md border border-white/30 px-3 py-2 text-sm disabled:opacity-50" disabled={loading} onClick={()=>void load(stateFilter)}>{text.refresh}</button></div>
      <nav className="mt-5 flex flex-wrap gap-2" aria-label={text.title}>{nav.map(([key,label])=><Link key={key} href={`/admin/retail/settlements/${key}`} aria-current={view===key?"page":undefined} className={`rounded-full px-4 py-2 text-sm ${view===key?"bg-white text-[#2f2923]":"bg-white/10 text-white hover:bg-white/20"}`}>{label}</Link>)}</nav>
    </header>
    <p className="mb-4 rounded-lg border border-[#ddcfbf] bg-[#fffaf4] px-4 py-3 text-sm text-[#6f6255]">{text.normalizedOnly}</p>
    {message&&<div role="status" className="mb-4 rounded-lg border border-[#d8c3a5] bg-[#fff8e8] px-4 py-3 text-sm">{message}</div>}{loading?<div className={sectionClass}>{text.loading}</div>:<>
      {view==="imports"&&<div className="grid gap-5 xl:grid-cols-[minmax(360px,0.9fr)_minmax(0,1.7fr)]"><div className="space-y-5"><section className={sectionClass}><h2 className="font-serif text-xl">{text.autoSync}</h2><p className="mt-2 text-sm text-[#6f6255]">{text.syncHelp}</p><label className="mt-5 block text-sm font-medium">{text.syncDays}<select className="mt-2 block w-full rounded-md border border-[#cdbda9] bg-[#fbf7f1] p-2" value={syncDays} onChange={(event)=>setSyncDays(Number(event.target.value))}><option value={1}>24 hours</option><option value={7}>7 days</option><option value={14}>14 days</option><option value={31}>31 days</option></select></label><button className="mt-4 rounded-md bg-[#2f2923] px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy} onClick={()=>void syncReport()}>{busy?text.syncing:text.syncNow}</button></section><details className={sectionClass}><summary className="cursor-pointer font-serif text-lg">{text.importTitle}</summary><p className="mt-2 text-sm text-[#6f6255]">{text.importHelp}</p><label className="mt-5 block text-sm font-medium" htmlFor="settlement-file">{text.sourceFile}</label><input id="settlement-file" className="mt-2 block w-full rounded-md border border-[#cdbda9] bg-[#fbf7f1] p-2 text-sm" type="file" accept=".csv,.json,text/csv,application/json" onChange={chooseFile}/>{file&&<div className="mt-4 rounded-lg bg-[#f6efe6] p-4 text-sm"><div><strong>{text.selected}:</strong> {file.name}</div><div><strong>{text.format}:</strong> {file.name.toLowerCase().endsWith(".json")?"JSON":"CSV"}</div><div><strong>{text.size}:</strong> {file.size.toLocaleString()} bytes</div></div>}{file&&!reviewing&&<button className="mt-4 rounded-md bg-[#2f2923] px-4 py-2 text-sm text-white" onClick={()=>setReviewing(true)}>{text.review}</button>}{reviewing&&file&&<div className="mt-4 flex flex-wrap gap-2"><button className="rounded-md bg-[#8a5a32] px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy||file.size>1_000_000} onClick={()=>void importReport()}>{busy?text.importing:text.confirmImport}</button><button className="rounded-md border border-[#cdbda9] px-4 py-2 text-sm" disabled={busy} onClick={()=>setReviewing(false)}>{text.cancel}</button></div>}</details></div><section className={sectionClass}><h2 className="font-serif text-xl">{text.imports}</h2>{(data.imports??[]).length?<Table headers={[text.file,text.rows,text.importedBy,text.importedAt,text.openExceptions,text.hash]} rows={data.imports??[]} render={(row)=><><Cell>{value(row,"source_name")}</Cell><Cell>{value(row,"row_count")}</Cell><Cell>{value(row,"imported_by")}</Cell><Cell>{date(row.imported_at,locale)}</Cell><Cell>{value(row,"open_exceptions")}</Cell><Cell mono>{value(row,"content_sha256").slice(0,12)}…</Cell></>}/>:<p className="mt-4 text-sm text-[#6f6255]">{text.noRecords}</p>}</section></div>}
      {view==="transactions"&&<div className="grid gap-5"><section className={sectionClass}><h2 className="font-serif text-xl">{text.transactions}</h2>{(data.transactions??[]).length?<Table headers={[text.transactionId,text.type,text.status,text.occurred,text.gross,text.fee,text.net,text.captureId,text.matchCount,text.openExceptions]} rows={data.transactions??[]} render={(row)=><><Cell mono>{value(row,"paypal_transaction_id")}</Cell><Cell>{value(row,"transaction_type")}</Cell><Cell>{value(row,"transaction_status")}</Cell><Cell>{date(row.occurred_at,locale)}</Cell><Cell>{money(row.gross_minor,row.currency,locale)}</Cell><Cell>{money(row.fee_minor,row.currency,locale)}</Cell><Cell>{money(row.net_minor,row.currency,locale)}</Cell><Cell mono>{value(row,"related_capture_id")}</Cell><Cell>{value(row,"match_count")}</Cell><Cell>{value(row,"open_exception_count")}</Cell></>}/>:<p className="mt-4 text-sm text-[#6f6255]">{text.noRecords}</p>}</section><section className={sectionClass}><h2 className="font-serif text-xl">{text.transactions} — {text.matchCount}</h2>{(data.matches??[]).length?<Table headers={[text.transactionId,text.matchKind,text.ledgerPosting,text.amount,text.reference]} rows={data.matches??[]} render={(row)=><><Cell mono>{value(row,"paypal_transaction_id")}</Cell><Cell>{value(row,"match_kind")}</Cell><Cell mono>{value(row,"ledger_id")} · {value(row,"ledger_kind")}</Cell><Cell>{money(row.amount_minor,row.currency,locale)}</Cell><Cell mono>{value(row,"paypal_reference")}</Cell></>}/>:<p className="mt-4 text-sm text-[#6f6255]">{text.noRecords}</p>}</section></div>}
      {view==="payouts"&&<div className="grid gap-5"><section className={sectionClass}><h2 className="font-serif text-xl">{text.payouts}</h2>{(data.payouts??[]).length?<Table headers={[text.payoutId,text.status,text.amount,text.occurred,text.importedAt]} rows={data.payouts??[]} render={(row)=><><Cell mono>{value(row,"paypal_payout_id")}</Cell><Cell>{value(row,"status")}</Cell><Cell>{money(row.amount_minor,row.currency,locale)}</Cell><Cell>{date(row.occurred_at,locale)}</Cell><Cell>{date(row.created_at,locale)}</Cell></>}/>:<p className="mt-4 text-sm text-[#6f6255]">{text.noRecords}</p>}</section><section className={sectionClass}><h2 className="font-serif text-xl">{text.items}</h2>{(data.payoutItems??[]).length?<Table headers={[text.payoutId,text.payoutItemId,text.transactionId,text.amount,text.created]} rows={data.payoutItems??[]} render={(row)=><><Cell mono>{value(row,"paypal_payout_id")}</Cell><Cell mono>{value(row,"paypal_payout_item_id")}</Cell><Cell mono>{value(row,"paypal_transaction_id")}</Cell><Cell>{money(row.amount_minor,"USD",locale)}</Cell><Cell>{date(row.created_at,locale)}</Cell></>}/>:<p className="mt-4 text-sm text-[#6f6255]">{text.noRecords}</p>}</section></div>}
      {view==="exceptions"&&<section className={sectionClass}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-serif text-xl">{text.exceptions}</h2><div className="flex gap-2"><button className={`rounded-full px-3 py-1.5 text-sm ${stateFilter==="open"?"bg-[#2f2923] text-white":"border border-[#cdbda9]"}`} onClick={()=>setStateFilter("open")}>{text.showOpen}</button><button className={`rounded-full px-3 py-1.5 text-sm ${stateFilter==="closed"?"bg-[#2f2923] text-white":"border border-[#cdbda9]"}`} onClick={()=>setStateFilter("closed")}>{text.showClosed}</button></div></div><div className="mt-4 grid gap-3">{(data.exceptions??[]).map((row)=><article key={String(row.id)} className="rounded-xl border border-[#e2d7cb] bg-[#fdfaf6] p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div><span className="block text-xs text-[#7c6d60]">{text.code}</span>{value(row,"code")}</div><div><span className="block text-xs text-[#7c6d60]">{text.transactionId}</span><span className="font-mono text-xs">{value(row,"paypal_transaction_id")}</span></div><div><span className="block text-xs text-[#7c6d60]">{text.captureId}</span><span className="font-mono text-xs">{value(row,"related_capture_id")}</span></div><div><span className="block text-xs text-[#7c6d60]">{text.amount}</span>{money(row.gross_minor,"USD",locale)}</div><div><span className="block text-xs text-[#7c6d60]">{text.created}</span>{date(row.created_at,locale)}</div></div>{stateFilter==="open"?<div className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor={`note-${row.id}`}>{text.closeNote}</label><input id={`note-${row.id}`} className="min-w-0 flex-1 rounded-md border border-[#cdbda9] px-3 py-2 text-sm" placeholder={text.closeNote} maxLength={500} value={notes[String(row.id)]??""} onChange={(event)=>setNotes((current)=>({...current,[String(row.id)]:event.target.value}))}/><button className="rounded-md bg-[#8a5a32] px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy||!(notes[String(row.id)]??"").trim()} onClick={()=>void closeException(String(row.id))}>{busy?text.closing:text.close}</button></div>:<div className="mt-3 text-sm text-[#6f6255]">{value(row,"close_note")} · {value(row,"closed_by")} · {date(row.closed_at,locale)}</div>}</article>)}{!(data.exceptions??[]).length&&<p className="text-sm text-[#6f6255]">{text.noRecords}</p>}</div></section>}
    </>}</div></div></AdminShell>;
}
